; [default]
; binding=someip
; libpath=/usr/local/lib:/usr/lib

; [local:v1:omnimetron.gpu.GpuUsageData:omnimetron.gpu.GpuUsageData]
; domain=local
; interface=v1.omnimetron.gpu.GpuUsageData
; instance=omnimetron.gpu.GpuUsageData



[default]
binding=someip
libpath=/usr/local/lib:/usr/lib

[local:omnimetron.gpu.GpuUsageData:v1.omnimetron.gpu.GpuUsageData]
service_id=0x1B1E
instance_id=0x567A